package com.hwr_goes_beuth.cardz.game.opponents;

import com.hwr_goes_beuth.cardz.entities.enums.Faction;
import com.hwr_goes_beuth.cardz.game.opponents.behaviors.AggressiveOpponentBehavior;
import com.hwr_goes_beuth.cardz.game.opponents.behaviors.PassiveOpponentBehavior;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

/**
 * Created by Project0rion on 30.12.2016.
 */
@Generated("generated by antlr")
public class OpponentRepository {

    public List<Opponent> getKnownOpponents() {
        List<Opponent> knownOpponents = new ArrayList<>();

        knownOpponents.add(new Opponent("Sharky McSharkface", Faction.Shark, new PassiveOpponentBehavior()));
        knownOpponents.add(new Opponent("Sharkinator", Faction.Shark, new AggressiveOpponentBehavior()));

        knownOpponents.add(new Opponent("Raptorion", Faction.Raptor, new AggressiveOpponentBehavior()));
        knownOpponents.add(new Opponent("Toothloosy", Faction.Raptor, new PassiveOpponentBehavior()));

        return knownOpponents;
    }
}
