package com.hwr_goes_beuth.cardz.game.cards;

import com.hwr_goes_beuth.cardz.entities.Card;
import com.hwr_goes_beuth.cardz.entities.enums.Faction;

import java.util.ArrayList;
import java.util.List;

import javax.annotation.Generated;

/**
 * Created by Project0rion on 23.12.2016.
 */
@Generated("generated by antlr")
public class CardRepository {

    private List<Card> knownCards;

    public CardRepository() {
        knownCards = new ArrayList<>();
        knownCards.add(createCard(Faction.Raptor, "Evil Raptor King", 6, 8, 10));
        knownCards.add(createCard(Faction.Raptor, "Mecha Mage", 2, 4, 5));
        knownCards.add(createCard(Faction.Raptor, "Raptor Archer", 3, 1, 2));
        knownCards.add(createCard(Faction.Shark, "Sharkowski", 5, 5, 9));
        knownCards.add(createCard(Faction.Shark, "Gunner Shark", 3, 4, 6));
        knownCards.add(createCard(Faction.Shark, "Terror Shark", 9, 2, 8));
    }

    private Card createCard(Faction faction, String name, int damage, int health, int cost) {
        Card newCard = new Card();
        newCard.setName(name);
        newCard.setFaction(faction);
        newCard.setDamage(damage);
        newCard.setHealth(health);
        newCard.setCost(cost);

        return newCard;
    }

    public Card getCardByName(String cardName, Faction faction) {
        for (Card card : knownCards) {
            if (card.getFaction() == faction && card.getName() == cardName)
                return card;
        }

        return null;
    }

    public List<Card> getKnownCards() {
        return knownCards;
    }
}
