package com.hwr_goes_beuth.cardz.game.cards;

import com.hwr_goes_beuth.cardz.core.dataAccess.DAOFactory;
import com.hwr_goes_beuth.cardz.entities.Card;
import com.hwr_goes_beuth.cardz.entities.Deck;
import com.hwr_goes_beuth.cardz.entities.Player;
import com.hwr_goes_beuth.cardz.entities.User;

import java.util.NoSuchElementException;

import javax.annotation.Generated;

/**
 * Created by Project0rion on 29.12.2016.
 */
@Generated("generated by antlr")
public class DeckRepository {

    private DAOFactory daoFactory;
    private CardRepository cardRepository;

    public DeckRepository(DAOFactory daoFactory, CardRepository cardRepository) {
        this.daoFactory = daoFactory;
        this.cardRepository = cardRepository;
    }

    public void createInitialSharkDeck(User user) {
        Deck sharkDeck = daoFactory.getUserDAO().getSharkDeck(user);

        addCardToDeck(sharkDeck, "Sharkowski");
        addCardToDeck(sharkDeck, "Sharkowski");
        addCardToDeck(sharkDeck, "Sharkowski");
        addCardToDeck(sharkDeck, "Terror Shark");
        addCardToDeck(sharkDeck, "Terror Shark");
        addCardToDeck(sharkDeck, "Gunner Shark");
        addCardToDeck(sharkDeck, "Gunner Shark");
        addCardToDeck(sharkDeck, "Gunner Shark");
    }

    public void createInitialRaptorDeck(User user) {
        Deck raptorDeck = daoFactory.getUserDAO().getRaptorDeck(user);

        addCardToDeck(raptorDeck, "Evil Raptor King");
        addCardToDeck(raptorDeck, "Mecha Mage");
        addCardToDeck(raptorDeck, "Mecha Mage");
        addCardToDeck(raptorDeck, "Mecha Mage");
        addCardToDeck(raptorDeck, "Raptor Archer");
        addCardToDeck(raptorDeck, "Raptor Archer");
        addCardToDeck(raptorDeck, "Raptor Archer");
        addCardToDeck(raptorDeck, "Raptor Archer");
    }

    public void createOpponentDeck(Player opponentPlayer) {
        if (opponentPlayer.getName() == "Sharky McSharkface")
            createSharkyMcSharkfaceDeck(opponentPlayer);
        else if (opponentPlayer.getName() == "Sharkinator")
            createSharkinatorDeck(opponentPlayer);
        else if (opponentPlayer.getName() == "Raptorion")
            createRaptorionDeck(opponentPlayer);
        else if (opponentPlayer.getName() == "Toothloosy")
            createToothloosyDeck(opponentPlayer);
        else
            throw new UnsupportedOperationException("there is no deck registered for opponent called " + opponentPlayer.getName());
    }

    private void createSharkyMcSharkfaceDeck(Player opponentPlayer) {
        Deck opponentDeck = daoFactory.getDeckDAO().getDeck(opponentPlayer.getDeckId());

        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Gunner Shark");
        addCardToDeck(opponentDeck, "Gunner Shark");
        addCardToDeck(opponentDeck, "Gunner Shark");
        addCardToDeck(opponentDeck, "Gunner Shark");
    }

    private void createSharkinatorDeck(Player opponentPlayer) {
        Deck opponentDeck = daoFactory.getDeckDAO().getDeck(opponentPlayer.getDeckId());

        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Sharkowski");
        addCardToDeck(opponentDeck, "Terror Shark");
        addCardToDeck(opponentDeck, "Terror Shark");
        addCardToDeck(opponentDeck, "Terror Shark");
        addCardToDeck(opponentDeck, "Terror Shark");
        addCardToDeck(opponentDeck, "Gunner Shark");
        addCardToDeck(opponentDeck, "Gunner Shark");
    }

    private void createRaptorionDeck(Player opponentPlayer) {
        Deck opponentDeck = daoFactory.getDeckDAO().getDeck(opponentPlayer.getDeckId());

        addCardToDeck(opponentDeck, "Evil Raptor King");
        addCardToDeck(opponentDeck, "Evil Raptor King");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
    }

    private void createToothloosyDeck(Player opponentPlayer) {
        Deck opponentDeck = daoFactory.getDeckDAO().getDeck(opponentPlayer.getDeckId());

        addCardToDeck(opponentDeck, "Raptor Archer");
        addCardToDeck(opponentDeck, "Raptor Archer");
        addCardToDeck(opponentDeck, "Raptor Archer");
        addCardToDeck(opponentDeck, "Raptor Archer");
        addCardToDeck(opponentDeck, "Raptor Archer");
        addCardToDeck(opponentDeck, "Evil Raptor King");
        addCardToDeck(opponentDeck, "Mecha Mage");
        addCardToDeck(opponentDeck, "Mecha Mage");
    }

    private void addCardToDeck(Deck playerDeck, String cardName) {
        Card newCard = daoFactory.getDeckDAO().createCardInDeck(playerDeck);
        Card repoCard = cardRepository.getCardByName(cardName, playerDeck.getFaction());

        if (repoCard == null)
            throw new NoSuchElementException("there is no known card called " + cardName);

        newCard.setName(repoCard.getName());
        newCard.setFaction(repoCard.getFaction());
        newCard.setDamage(repoCard.getDamage());
        newCard.setHealth(repoCard.getHealth());
        newCard.setCost(repoCard.getCost());

        daoFactory.getCardDAO().updateCard(newCard);
    }
}
